// <auto-generated />
using System;
using EjemploEventSourcing.Infrastructure.Repositorios;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EjemploEventSourcing.Migrations
{
    [DbContext(typeof(EventStoreDBContext))]
    [Migration("20201020200905_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EjemploEventSourcing.Infraestructura.Repositorios.Aggregate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("LastVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Aggregates");
                });

            modelBuilder.Entity("EjemploEventSourcing.Infraestructura.Repositorios.Event", b =>
                {
                    b.Property<string>("AggregateId")
                        .HasColumnType("text");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("integer");

                    b.Property<string>("AggregateData")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("DateTimeCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("MetaData")
                        .HasColumnType("jsonb");

                    b.HasKey("AggregateId", "AggregateVersion");

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
