// <auto-generated />
using System;
using EjemploEventSourcing.Infrastructure.Repositorios;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EjemploEventSourcing.Migrations
{
    [DbContext(typeof(EventStoreDBContext))]
    partial class EventStoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EjemploEventSourcing.Infrastructure.Repositorios.Aggregate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("LastVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Aggregates");
                });

            modelBuilder.Entity("EjemploEventSourcing.Infrastructure.Repositorios.Event", b =>
                {
                    b.Property<string>("AggregateId")
                        .HasColumnType("text");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("integer");

                    b.Property<string>("AggregateData")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("DateTimeCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("MetaData")
                        .HasColumnType("jsonb");

                    b.HasKey("AggregateId", "AggregateVersion");

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
